export const events = [
  {
    slug: "swimrunman-gorges-du-verdon",
    name: "Swimrunman aux Gorges du Verdon",
    location: "Salles-sur-Verdon (83)",
    dates: "09-10 mai 2026",
    dateStart: "2026-05-09",
    dateEnd: "2026-05-10",
    type: "sportif",
    description: "Plonge au cœur des Gorges du Verdon pour une aventure swimrun inoubliable. Aide à l'organisation de cette course unique mêlant nage et course en pleine nature.",
    image: "/images/events/srman-calanques.webp",
    spots: 40,
    spotsFilled: 12,
  },
  {
    slug: "openlakes",
    name: "OpenLakes",
    location: "Miribel Jonage (69)",
    dates: "16-17 mai 2026",
    dateStart: "2026-05-16",
    dateEnd: "2026-05-17",
    type: "sportif",
    description: "Festival de nage en eau libre au Grand Parc de Miribel-Jonage. Un événement convivial aux portes de Lyon.",
    image: "/images/events/benevoles-openlakes.webp",
    spots: 30,
    spotsFilled: 8,
  },
  {
    slug: "colnago-gf-mont-ventoux",
    name: "Colnago GF Mont Ventoux",
    location: "Vaison-la-Romaine (84)",
    dates: "04-07 juin 2026",
    dateStart: "2026-06-04",
    dateEnd: "2026-06-07",
    type: "sportif",
    description: "La mythique Gran Fondo cycliste sur les pentes du Mont Ventoux. 4 jours d'événement, des milliers de passionnés.",
    image: "/images/events/gf-ventoux.jpg",
    spots: 80,
    spotsFilled: 35,
  },
  {
    slug: "lyon-street-food-festival",
    name: "Lyon Street Food Festival",
    location: "Lyon (69)",
    dates: "11-14 juin 2026",
    dateStart: "2026-06-11",
    dateEnd: "2026-06-14",
    type: "culturel",
    description: "Le plus grand festival de street food de France ! Rejoins l'équipe bénévole pour 4 jours de gastronomie et de fête à Lyon.",
    image: "/images/events/lyon-street-food.jpg",
    spots: 120,
    spotsFilled: 67,
  },
  {
    slug: "swimrunman-lac-vassiviere",
    name: "Swimrunman Lac de Vassivière",
    location: "Peyrat-le-Château (87)",
    dates: "20-21 juin 2026",
    dateStart: "2026-06-20",
    dateEnd: "2026-06-21",
    type: "sportif",
    description: "Swimrun au cœur du Limousin sur le magnifique Lac de Vassivière.",
    image: "/images/events/swimrunman-vassiviere.jpg",
    spots: 35,
    spotsFilled: 10,
  },
  {
    slug: "marathon-du-vercors",
    name: "Marathon du Vercors",
    location: "Lans (38)",
    dates: "26-28 juin 2026",
    dateStart: "2026-06-26",
    dateEnd: "2026-06-28",
    type: "sportif",
    description: "Course mythique sur le plateau du Vercors. Un week-end sportif dans un cadre naturel exceptionnel.",
    image: "/images/events/vercors.jpg",
    spots: 50,
    spotsFilled: 22,
  },
  {
    slug: "arcteryx-alpine-academy",
    name: "Arc'teryx Alpine Academy",
    location: "Chamonix (74)",
    dates: "30 juin - 06 juillet 2026",
    dateStart: "2026-06-30",
    dateEnd: "2026-07-06",
    type: "sportif",
    description: "Semaine de formation et d'aventure en montagne à Chamonix. Alpinisme, escalade et trail au pied du Mont-Blanc.",
    image: "/images/events/arcteryx.png",
    spots: 60,
    spotsFilled: 28,
  },
  {
    slug: "yotta",
    name: "Yotta",
    location: "Vichy (03)",
    dates: "16-19 juillet 2026",
    dateStart: "2026-07-16",
    dateEnd: "2026-07-19",
    type: "sportif",
    description: "Événement multisport à Vichy. Une expérience bénévole riche au cœur de l'Allier.",
    image: "/images/events/event-sport.jpg",
    spots: 45,
    spotsFilled: 15,
  },
  {
    slug: "triathlon-de-la-madeleine",
    name: "Triathlon de la Madeleine",
    location: "St Rémy de Maurienne (73)",
    dates: "21 août 2026",
    dateStart: "2026-08-21",
    dateEnd: "2026-08-21",
    type: "sportif",
    description: "Triathlon au pied du Col de la Madeleine en Savoie. Un défi sportif dans un cadre alpin grandiose.",
    image: "/images/events/hero-benevoles.jpg",
    spots: 30,
    spotsFilled: 9,
  },
  {
    slug: "festival-danse-avoriaz",
    name: "Festival de Danse d'Avoriaz",
    location: "Avoriaz (74)",
    dates: "21-28 août 2026",
    dateStart: "2026-08-21",
    dateEnd: "2026-08-28",
    type: "culturel",
    description: "Une semaine de danse en altitude ! Spectacles, ateliers et rencontres dans le cadre unique d'Avoriaz.",
    image: "/images/events/event-outdoor.jpg",
    spots: 50,
    spotsFilled: 48,
  },
  {
    slug: "triathlon-t100",
    name: "Triathlon T100",
    location: "Saint-Raphaël (83)",
    dates: "18-20 septembre 2026",
    dateStart: "2026-09-18",
    dateEnd: "2026-09-20",
    type: "sportif",
    description: "Compétition internationale de triathlon sur la Côte d'Azur.",
    image: "/images/events/visuel-site.jpg",
    spots: 70,
    spotsFilled: 30,
  },
  {
    slug: "ventouxman",
    name: "Ventouxman",
    location: "Monteux (84)",
    dates: "18-20 septembre 2026",
    dateStart: "2026-09-18",
    dateEnd: "2026-09-20",
    type: "sportif",
    description: "Triathlon longue distance au pied du Géant de Provence. Un événement mythique.",
    image: "/images/events/ventouxman-benevole.png",
    spots: 40,
    spotsFilled: 18,
  },
  {
    slug: "ultra-trail-grand-colombier",
    name: "Ultra Trail Grand Colombier",
    location: "Culoz (01)",
    dates: "24-27 septembre 2026",
    dateStart: "2026-09-24",
    dateEnd: "2026-09-27",
    type: "sportif",
    description: "Ultra-trail dans le massif du Grand Colombier, aux confins du Bugey. Sentiers, forêts et panoramas.",
    image: "/images/events/utgc.png",
    spots: 55,
    spotsFilled: 20,
  },
  {
    slug: "high-five-festival",
    name: "High Five Festival",
    location: "Annecy (74)",
    dates: "01-04 octobre 2026",
    dateStart: "2026-10-01",
    dateEnd: "2026-10-04",
    type: "culturel",
    description: "Festival international du film de montagne et d'aventure à Annecy. Projections, rencontres et passion.",
    image: "/images/events/lafffr.png",
    spots: 40,
    spotsFilled: 25,
  },
  {
    slug: "la-saintelyon",
    name: "La SaintéLyon",
    location: "Lyon (69)",
    dates: "27-28 novembre 2026",
    dateStart: "2026-11-27",
    dateEnd: "2026-11-28",
    type: "sportif",
    description: "La course nocturne mythique de Saint-Étienne à Lyon. 20 000 participants, une aventure humaine incroyable.",
    image: "/images/events/benevoles-saintelyon.jpg",
    spots: 150,
    spotsFilled: 95,
  },
  {
    slug: "rock-on-snow",
    name: "Rock On Snow",
    location: "Avoriaz (74)",
    dates: "09-13 décembre 2026",
    dateStart: "2026-12-09",
    dateEnd: "2026-12-13",
    type: "culturel",
    description: "Festival de musique sur neige à Avoriaz. Rock, électro et bonne humeur en altitude.",
    image: "/images/events/groupe-benevoles.jpg",
    spots: 45,
    spotsFilled: 20,
  },
];

export const partners = [
  { name: "Avoriaz", logo: "/images/partners/avoriaz.png" },
  { name: "OSL", logo: "/images/partners/osl.png" },
  { name: "Colnago GF Series", logo: "/images/partners/colnago-gf.jpg" },
  { name: "Saint-François-Longchamp", logo: "/images/partners/saint-francois.webp" },
  { name: "GF Provence", logo: "/images/partners/gf-provence.png" },
  { name: "Les Intenses Sessions", logo: "/images/partners/intenses-sessions.png" },
  { name: "UTGC", logo: "/images/partners/utgc-logo.png" },
  { name: "GF Series", logo: "/images/partners/gf-series.webp" },
];

export const galleryImages = [
  "/images/gallery/0_frame.jpg",
  "/images/gallery/2_frame.jpg",
  "/images/gallery/4_frame.jpg",
  "/images/gallery/6_frame.jpg",
  "/images/gallery/8_frame.jpg",
  "/images/gallery/10_frame.jpg",
  "/images/gallery/12_frame.jpg",
  "/images/gallery/14_frame.jpg",
  "/images/gallery/16_frame.jpg",
  "/images/gallery/18_frame.jpg",
  "/images/gallery/20_frame.jpg",
  "/images/gallery/22_frame.jpg",
  "/images/gallery/24_frame.jpg",
  "/images/gallery/26_frame.jpg",
  "/images/gallery/28_frame.jpg",
  "/images/gallery/30_frame.jpg",
  "/images/gallery/32_frame.jpg",
  "/images/gallery/34_frame.jpg",
  "/images/gallery/36_frame.jpg",
  "/images/gallery/38_frame.jpg",
  "/images/gallery/40_frame.jpg",
  "/images/gallery/43_frame.jpg",
];

export const teamMembers = {
  board: [
    { name: "Anne", role: "Présidente", image: "/images/team/member-1.jpg" },
    { name: "Thierry", role: "Vice-président", image: "/images/team/thierry.png" },
    { name: "Odile", role: "Trésorière", image: "/images/team/odile.png" },
    { name: "Françoise", role: "Secrétaire", image: "/images/team/member-4.jpg" },
    { name: "Frédéric", role: "Comptable", image: "/images/team/member-5.jpg" },
    { name: "Sylvie", role: "Chargée de communication", image: "/images/team/member-6.jpg" },
    { name: "Aurélie", role: "Administratrice", image: "/images/team/member-3.jpg" },
  ],
  staff: [
    { name: "Quentin Willems", role: "Directeur", focus: "Développement & Engagement", email: "quentin@amicaledesbenevoles.org", phone: "06 88 65 19 60", image: "/images/team/member-2.jpg" },
    { name: "Jordan Finoel", role: "Chef de projet", focus: "Production & Stratégie d'affectation", phone: "06 20 33 10 09", image: "/images/team/jordan.png" },
    { name: "Maëlle Dufresnes", role: "Cheffe de projet", focus: "Animation & Mobilisation de communauté", image: "/images/team/member-1.jpg" },
  ],
};

export const testimonials = [
  {
    name: "Ambre",
    org: "AREMACS",
    text: "Les bénévoles ont été très attentifs et super motivés. L'Amicale a su recruter des profils engagés qui ont fait la différence sur notre événement.",
  },
  {
    name: "Mathieu Kurtz",
    org: "High Five Festival",
    text: "L'équipe a su analyser et apporter des correctifs pour améliorer l'expérience. Je suis satisfait de la prestation de l'ADB sur le volume et la gestion des bénévoles.",
  },
];

export const stats = [
  { label: "De satisfaction", value: 95, suffix: "%" },
  { label: "Bénévoles mobilisés", value: 3000, suffix: "+" },
  { label: "Journées bénévoles", value: 8500, suffix: "" },
  { label: "Événements", value: 18, suffix: "" },
  { label: "De fidélisation", value: 62, suffix: "%" },
];
