/* THIS FILE IS GENERATED BY PAYLOAD. DO NOT EDIT IT BY HAND. */
import { VercelBlobClientUploadHandler as VercelBlobClientUploadHandler_16c82c5e8a0d4ef7d7a3dfcd2c7b3354 } from "@payloadcms/storage-vercel-blob/client";

export const importMap = {
  "@payloadcms/storage-vercel-blob/client#VercelBlobClientUploadHandler":
    VercelBlobClientUploadHandler_16c82c5e8a0d4ef7d7a3dfcd2c7b3354,
};
